# Generated by Django 3.1.1 on 2020-11-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
