# Generated by Django 3.1 on 2020-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('contact', models.CharField(max_length=100)),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
    ]
