# Generated by Django 3.1 on 2020-10-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
