# Generated by Django 3.1 on 2020-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20201015_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]