# Generated by Django 3.1 on 2020-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_usermeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeeting',
            name='is_join',
            field=models.BooleanField(default=False),
        ),
    ]
