# Generated by Django 3.1.1 on 2020-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_usermeeting_is_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pdf',
            field=models.FileField(default=2, upload_to='doc/pdfs'),
            preserve_default=False,
        ),
    ]
