# Generated by Django 3.1.1 on 2020-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_meeting_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='pdf',
            new_name='upload',
        ),
    ]
