# Generated by Django 3.1 on 2020-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_meeting_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='doc/pdfs'),
        ),
    ]
